<?php
namespace thriftgen\service;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface PostServiceIf {
  /**
   * @param \thriftgen\domain\Query $query
   * @return \thriftgen\domain\Post[]
   */
  public function find(\thriftgen\domain\Query $query);
  /**
   * @param \thriftgen\domain\Post $post
   * @return \thriftgen\domain\CUDResult
   */
  public function create(\thriftgen\domain\Post $post);
  /**
   * @param \thriftgen\domain\Post $post
   * @param \thriftgen\domain\Tag[] $tagList
   * @return \thriftgen\domain\CUDResult
   */
  public function createWithTags(\thriftgen\domain\Post $post, array $tagList);
  /**
   * @param \thriftgen\domain\Post $post
   * @return \thriftgen\domain\CUDResult
   */
  public function update(\thriftgen\domain\Post $post);
  /**
   * @param \thriftgen\domain\Post $post
   * @param \thriftgen\domain\Tag[] $tagList
   * @return \thriftgen\domain\CUDResult
   */
  public function updateWithTags(\thriftgen\domain\Post $post, array $tagList);
  /**
   * @param int $id
   * @return \thriftgen\domain\CUDResult
   */
  public function deleteById($id);
}


